# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2afa39a202d298a36e67a060afc79ba652ea59afccacd9d8a59def14112dd25fb9dc158818da060973cf79305b575fba5b9839a773edf83a7138a917749a93a5

test:
  secret_key_base: 88a402d57a13e924e44c7a6c60dabacb3b33f364037d560005b3ebedf4723bb7398eedb5cc8eb802fc0c24662c01540f0db7a23e8614ecfafaa4f3c240b7452d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
